### ISSUE TITLE
fb and fop score for my segmentation result

### ISSUE THREAD

**Issue by sankar19** [jponttuset/seism#6]
Hi,

I have an initial over segmentation result with labels going from 1,2,..N. I then create an hierarchy of results by merging them (parameters - 1 through 10). segs{1} = oversegment ... segs{10} = coarsesegment

I found fb using your code and fb from BSR code of  P. Arbelaez PAMI paper. I get different results:
PAMI paper:
ODS - 0.68 OIS - 0.71

Your code:
odsF-0.024 oisF-0.024

I am using source io read_one_lep.m. 

Can you please help me figure out, if I am using your code properly to evaluate my results. I have shared the test results in this folder: https://www.dropbox.com/sh/fa2gl9uknqqf6ng/AAD9Hlk6mlFUVWEZAOZEWZqYa

Thanks for your time.
Sankar

**Comment by jponttuset** [comment]
Hi Sankar!

I downloaded your results and they look good to me, I can read them properly.
Can you tell me exactly how do you get these numbers?

If you use the scripts in SEISM, you should add a file in the "parameters" folder with your parameters, which in your case should be 1,...,10 because you always have 10 partitions in the hierarchy.

**Comment by sankar19** [comment]
Hi,

I included a text file in the parameters folder with 1,2...10 in each line (dpgradrgl.txt)

Also I added 
        methods(end+1).name = 'dpgradrgl';             methods(end).io_func = @read_one_lep;      methods(end).legend = methods(end).name;  methods(end).type = 'segmentation';

and lines (jj=length(methods):length(methods)):

    for ii=1:length(measures)
        for jj=length(methods):length(methods)
            % Contours only in 'fb'
            is_cont = strcmp(methods(ii).type,'contour');
            if strcmp(measures{ii},'fb') || ~is_cont
                if exist('cat_id','var')
                    eval_method_all_params(methods(jj).name, measures{ii}, methods(jj).io_func, database, gt_set, is_cont, cat_id);
                else
                    eval_method_all_params(methods(jj).name, measures{ii}, methods(jj).io_func, database, gt_set, is_cont);
                end
            end
        end
    end


The m file is in: https://www.dropbox.com/sh/fa2gl9uknqqf6ng/AAD9Hlk6mlFUVWEZAOZEWZqYa

**Comment by jponttuset** [comment]
Hi Sankar!

Thanks for the patience, and sorry for the bug. In principle I solved it in the latest commit, and now I get this result for your method, which matches the one you mentioned.
```dgradrgl:        [odsF:0.681 oisF:0.706 AP:0.292]```

In the snippet you sent above, you should change:
```is_cont = strcmp(methods(ii).type,'contour');```
Into
```is_cont = strcmp(methods(jj).type,'contour');```

Please let me know if this solved the issue.

Best,
Jordi

**Comment by jponttuset** [comment]
Hi again, please note that I updated the comment, I had a mistake :)

**Comment by sankar19** [comment]
Hi,

Thanks your time. I ran the algorithm with modifications (in two of the files) in the commit. Through your code, I was able to get fb score similar to PAMI paper. 

I will go over the results on fop. I need to go over the paper to understand the fop score (I have read PAMI paper and they have region scores. I just need to check if the fop evaluation is for comparing image segmentation algorithms or single object proposal)

Thanks for the evaluation methodologies and website.

**Comment by jponttuset** [comment]
Awesome! 
Fop is for comparing segmentation directly, not proposals. I'd recommend using both Fb and Fop in parallel, they show different things.

**Comment by sankar19** [comment]
Hi,

If possible, can you please add the results for COB (text files - seism/results/pr_curves/BSDS500/ seism/results/BSDS500/). I can only find the results for Pascal.

Or I can run the evaluation code with COB UCM downloaded from the website. 

Thanks,
Sankar

**Comment by kmaninis** [comment]
Hi Sankar,

COB results for BSDS500 are added now.

Have a nice day,
Kevis
